# Generated by Django 5.1.4 on 2024-12-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20241209_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemicalinventory',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
