# Generated by Django 5.1.4 on 2024-12-12 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_production_metrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('Preventive', 'Preventive Maintenance'), ('Corrective', 'Corrective Maintenance'), ('Emergency', 'Emergency Repair'), ('Inspection', 'Routine Inspection')], max_length=50)),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_hours', models.DecimalField(decimal_places=1, max_digits=5)),
                ('technician', models.CharField(max_length=100)),
                ('parts_replaced', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machinery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='dashboard.machinery')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='dashboard_m_date_d1206d_idx'), models.Index(fields=['machinery', 'date'], name='dashboard_m_machine_3c9c3d_idx')],
            },
        ),
    ]
