# Generated by Django 5.1.4 on 2024-12-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_maintenancerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinery',
            name='operating_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='machinery',
            name='status',
            field=models.CharField(choices=[('Operational', 'Operational'), ('Under Maintenance', 'Under Maintenance'), ('Offline', 'Offline'), ('Out of Service', 'Out of Service')], max_length=50),
        ),
    ]
