# Generated by Django 5.1.4 on 2024-12-12 19:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_machinery__next_maintenance_due'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machinery',
            options={},
        ),
        migrations.AlterModelOptions(
            name='maintenancerecord',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='maintenancerecord',
            name='dashboard_m_date_d1206d_idx',
        ),
        migrations.RemoveIndex(
            model_name='maintenancerecord',
            name='dashboard_m_machine_3c9c3d_idx',
        ),
        migrations.RemoveField(
            model_name='machinery',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='machinery',
            name='next_maintenance',
        ),
        migrations.RemoveField(
            model_name='machinery',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='machinery',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='maintenancerecord',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='maintenancerecord',
            name='parts_replaced',
        ),
        migrations.RemoveField(
            model_name='maintenancerecord',
            name='technician',
        ),
        migrations.RemoveField(
            model_name='maintenancerecord',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='machinery',
            name='_next_maintenance_due',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='machinery',
            name='efficiency',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='machinery',
            name='last_maintenance',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='machinery',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='machinery',
            name='status',
            field=models.CharField(choices=[('Operational', 'Operational'), ('Under Maintenance', 'Under Maintenance'), ('Out of Service', 'Out of Service')], default='Operational', max_length=20),
        ),
        migrations.AlterField(
            model_name='machinery',
            name='type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='duration_hours',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
