# Generated by Django 5.1.4 on 2024-12-12 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_machinery_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount_used', models.DecimalField(decimal_places=2, max_digits=10)),
                ('process', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='dashboard.chemicalinventory')),
            ],
            options={
                'verbose_name_plural': 'Chemical Usage',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Operational', 'Operational'), ('Under Maintenance', 'Under Maintenance'), ('Out of Service', 'Out of Service')], max_length=20)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machinery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='dashboard.machinery')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
