# Generated by Django 5.1.4 on 2024-12-13 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_safetyincident_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionmetrics',
            name='gold_smelted',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
