# Generated by Django 5.1.4 on 2024-12-13 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_populate_gold_smelted_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExplosivesInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Primary', 'Primary Explosive'), ('Secondary', 'Secondary Explosive'), ('Detonator', 'Detonator'), ('Booster', 'Booster'), ('Other', 'Other')], max_length=100)),
                ('current_stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimum_required', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_restocked', models.DateField(auto_now=True)),
                ('supplier', models.CharField(blank=True, max_length=200, null=True)),
                ('storage_location', models.CharField(max_length=200)),
                ('license_number', models.CharField(max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Explosives Inventories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExplosivesUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount_used', models.DecimalField(decimal_places=2, max_digits=10)),
                ('blast_location', models.CharField(max_length=200)),
                ('blast_purpose', models.CharField(max_length=200)),
                ('authorized_by', models.CharField(max_length=200)),
                ('weather_conditions', models.CharField(blank=True, max_length=100, null=True)),
                ('rock_type', models.CharField(blank=True, max_length=100, null=True)),
                ('blast_pattern', models.CharField(blank=True, max_length=100, null=True)),
                ('effectiveness_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('explosive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='dashboard.explosivesinventory')),
            ],
            options={
                'verbose_name_plural': 'Explosives Usage',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
