# Generated by Django 5.1.4 on 2024-12-21 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_merge_20241215_0300'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductionMetrics',
        ),
        migrations.DeleteModel(
            name='StockpileVolume',
        ),
    ]
