# Generated by Django 5.1.4 on 2024-12-24 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_remove_equipment_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaintenanceRecord',
        ),
        migrations.DeleteModel(
            name='Machinery',
        ),
    ]
