# Generated by Django 5.1.4 on 2024-12-23 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_remove_machinery_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardwidget',
            name='type',
            field=models.CharField(choices=[('production_chart', 'Production Chart'), ('safety_summary', 'Safety Summary'), ('chemical_inventory', 'Chemical Inventory'), ('financial_overview', 'Financial Overview')], max_length=30),
        ),
    ]
