# Generated by Django 5.1.4 on 2024-12-09 18:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining_operations', '0003_dailyexpense_energyconsumption_environmentalmetric_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldMillingEquipmentNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('operational', 'Operational'), ('maintenance', 'Maintenance'), ('offline', 'Offline')], max_length=20)),
                ('last_maintenance', models.DateTimeField(blank=True, null=True)),
                ('next_maintenance', models.DateTimeField(blank=True, null=True)),
                ('efficiency', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HeavyMachineryNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('operational', 'Operational'), ('maintenance', 'Maintenance'), ('offline', 'Offline')], max_length=20)),
                ('last_maintenance', models.DateTimeField(blank=True, null=True)),
                ('next_maintenance', models.DateTimeField(blank=True, null=True)),
                ('hours_operated', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MiningChemicalNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('current_stock', models.FloatField()),
                ('minimum_required', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('last_restocked', models.DateTimeField(default=django.utils.timezone.now)),
                ('hazard_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SafetyIncidentNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('workers_affected', models.IntegerField(default=0)),
                ('resolved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DailyChemicalsUsedNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount_used', models.FloatField()),
                ('purpose', models.CharField(max_length=200)),
                ('operator', models.CharField(max_length=100)),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mining_operations.miningchemicalnew')),
            ],
        ),
    ]
