# Generated by Django 5.1.4 on 2024-12-10 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining_operations', '0004_goldmillingequipmentnew_heavymachinerynew_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('electricity_kwh', models.FloatField(help_text='Daily electricity consumption in kilowatt-hours', validators=[django.core.validators.MinValueValidator(0)])),
                ('electricity_cost', models.DecimalField(decimal_places=2, help_text='Daily electricity cost in $', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('diesel_liters', models.FloatField(help_text='Daily diesel consumption in liters', validators=[django.core.validators.MinValueValidator(0)])),
                ('diesel_cost', models.DecimalField(decimal_places=2, help_text='Daily diesel cost in $', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_cost', models.DecimalField(decimal_places=2, help_text='Total energy cost for the day in $', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name_plural': 'Energy Usage',
                'ordering': ['-date'],
            },
        ),
        migrations.RemoveField(
            model_name='dailychemicalsusednew',
            name='chemical',
        ),
        migrations.RemoveField(
            model_name='dailyenergyconsumption',
            name='department',
        ),
        migrations.RemoveField(
            model_name='dailyexpenses',
            name='department',
        ),
        migrations.DeleteModel(
            name='EnergyConsumption',
        ),
        migrations.DeleteModel(
            name='GoldMillingEquipmentNew',
        ),
        migrations.DeleteModel(
            name='HeavyMachineryNew',
        ),
        migrations.RemoveField(
            model_name='historicaldailyenergyconsumption',
            name='department',
        ),
        migrations.RemoveField(
            model_name='historicaldailyenergyconsumption',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaldailyexpenses',
            name='department',
        ),
        migrations.RemoveField(
            model_name='historicaldailyexpenses',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='SafetyIncidentNew',
        ),
        migrations.DeleteModel(
            name='DailyChemicalsUsedNew',
        ),
        migrations.DeleteModel(
            name='MiningChemicalNew',
        ),
        migrations.DeleteModel(
            name='DailyEnergyConsumption',
        ),
        migrations.DeleteModel(
            name='DailyExpenses',
        ),
        migrations.DeleteModel(
            name='HistoricalDailyEnergyConsumption',
        ),
        migrations.DeleteModel(
            name='HistoricalDailyExpenses',
        ),
    ]
