# Generated by Django 5.1.4 on 2024-12-10 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining_operations', '0005_energyusage_remove_dailychemicalsusednew_chemical_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailylaborcost',
            name='department',
        ),
        migrations.RemoveField(
            model_name='historicaldailylaborcost',
            name='department',
        ),
        migrations.RemoveField(
            model_name='historicaldailylaborcost',
            name='history_user',
        ),
        migrations.AlterModelOptions(
            name='labormetric',
            options={'ordering': ['-date', 'shift']},
        ),
        migrations.AddField(
            model_name='labormetric',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mining_operations.miningdepartment'),
        ),
        migrations.AddField(
            model_name='labormetric',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='labormetric',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labormetric',
            name='total_labor_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='labormetric',
            name='hours_worked',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='labormetric',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='labormetric',
            name='productivity_index',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='labormetric',
            name='shift',
            field=models.CharField(choices=[('MORNING', 'Morning Shift'), ('AFTERNOON', 'Afternoon Shift'), ('NIGHT', 'Night Shift')], default='MORNING', max_length=20),
        ),
        migrations.AlterField(
            model_name='labormetric',
            name='workers_present',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='labormetric',
            index=models.Index(fields=['date'], name='mining_oper_date_053fb0_idx'),
        ),
        migrations.AddIndex(
            model_name='labormetric',
            index=models.Index(fields=['department'], name='mining_oper_departm_2fc6b9_idx'),
        ),
        migrations.AddIndex(
            model_name='labormetric',
            index=models.Index(fields=['shift'], name='mining_oper_shift_d4c51d_idx'),
        ),
        migrations.DeleteModel(
            name='DailyLaborCost',
        ),
        migrations.DeleteModel(
            name='HistoricalDailyLaborCost',
        ),
    ]
