# Generated by Django 5.1.4 on 2024-12-13 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining_operations', '0008_alter_safetyincident_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyproductionlog',
            name='gold_smelted_grams',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount of gold smelted in grams', max_digits=10),
        ),
        migrations.AddField(
            model_name='historicaldailyproductionlog',
            name='gold_smelted_grams',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount of gold smelted in grams', max_digits=10),
        ),
    ]
