# Generated by Django 5.1.4 on 2024-12-13 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mining_operations', '0009_dailyproductionlog_gold_smelted_grams_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyproductionlog',
            name='gold_smelted_grams',
        ),
        migrations.RemoveField(
            model_name='historicaldailyproductionlog',
            name='gold_smelted_grams',
        ),
    ]
