# Generated by Django 5.1.4 on 2024-12-13 17:51

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining_operations', '0010_remove_dailyproductionlog_gold_smelted_grams_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalminingdepartment',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Mining Department', 'verbose_name_plural': 'historical Mining Departments'},
        ),
        migrations.AlterModelOptions(
            name='labormetric',
            options={'ordering': ['-date', 'shift'], 'verbose_name': 'Labor Metric', 'verbose_name_plural': 'Labor Metrics'},
        ),
        migrations.AlterModelOptions(
            name='miningdepartment',
            options={'verbose_name': 'Mining Department', 'verbose_name_plural': 'Mining Departments'},
        ),
        migrations.RemoveField(
            model_name='labormetric',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='labormetric',
            name='total_labor_cost',
        ),
        migrations.AddField(
            model_name='labormetric',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='labormetric',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dailychemicalsused',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mining_operations.miningdepartment'),
        ),
        migrations.AlterField(
            model_name='dailyexplosivesused',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mining_operations.miningdepartment'),
        ),
        migrations.AlterField(
            model_name='historicalminingdepartment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historicalminingdepartment',
            name='type',
            field=models.CharField(choices=[('extraction', 'Extraction'), ('processing', 'Processing'), ('maintenance', 'Maintenance'), ('safety', 'Safety'), ('logistics', 'Logistics')], max_length=20),
        ),
        migrations.AlterField(
            model_name='labormetric',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labor_metrics', to='mining_operations.miningdepartment'),
        ),
        migrations.AlterField(
            model_name='labormetric',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=25.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='miningdepartment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='miningdepartment',
            name='type',
            field=models.CharField(choices=[('extraction', 'Extraction'), ('processing', 'Processing'), ('maintenance', 'Maintenance'), ('safety', 'Safety'), ('logistics', 'Logistics')], max_length=20),
        ),
        migrations.AlterField(
            model_name='safetyincident',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_incidents_ops', to='mining_operations.miningdepartment'),
        ),
        migrations.CreateModel(
            name='HistoricalLaborMetric',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('MORNING', 'Morning Shift'), ('AFTERNOON', 'Afternoon Shift'), ('NIGHT', 'Night Shift')], default='MORNING', max_length=20)),
                ('workers_present', models.IntegerField(default=0)),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('productivity_index', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('safety_incidents', models.IntegerField(default=0)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=25.0, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('department', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mining_operations.miningdepartment')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Labor Metric',
                'verbose_name_plural': 'historical Labor Metrics',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
