# Generated by Django 5.1.4 on 2024-12-13 19:24

from django.db import migrations
from django.utils import timezone

def create_shifts_and_update_references(apps, schema_editor):
    LaborMetric = apps.get_model('mining_operations', 'LaborMetric')
    Shift = apps.get_model('mining_operations', 'Shift')
    MiningDepartment = apps.get_model('mining_operations', 'MiningDepartment')
    db_alias = schema_editor.connection.alias

    # Create default shifts for each department
    shift_mapping = {}
    departments = MiningDepartment.objects.using(db_alias).all()

    for department in departments:
        morning_shift = Shift.objects.using(db_alias).create(
            name='Morning Shift',
            start_time='06:00',
            end_time='14:00',
            department=department,
            created_at=timezone.now(),
            updated_at=timezone.now()
        )
        afternoon_shift = Shift.objects.using(db_alias).create(
            name='Afternoon Shift',
            start_time='14:00',
            end_time='22:00',
            department=department,
            created_at=timezone.now(),
            updated_at=timezone.now()
        )
        night_shift = Shift.objects.using(db_alias).create(
            name='Night Shift',
            start_time='22:00',
            end_time='06:00',
            department=department,
            created_at=timezone.now(),
            updated_at=timezone.now()
        )
        shift_mapping[department.id] = {
            'MORNING': morning_shift,
            'AFTERNOON': afternoon_shift,
            'NIGHT': night_shift
        }

def reverse_shifts_and_references(apps, schema_editor):
    Shift = apps.get_model('mining_operations', 'Shift')
    db_alias = schema_editor.connection.alias
    Shift.objects.using(db_alias).all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('mining_operations', '0013_convert_shift_choices_to_model'),
    ]

    operations = [
        migrations.RunPython(create_shifts_and_update_references, reverse_shifts_and_references),
    ]
