# Generated by Django 5.1.4 on 2024-12-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining_operations', '0015_update_labor_metrics_shifts'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallabormetric',
            name='old_shift',
            field=models.CharField(blank=True, choices=[('MORNING', 'Morning Shift'), ('AFTERNOON', 'Afternoon Shift'), ('NIGHT', 'Night Shift')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='labormetric',
            name='old_shift',
            field=models.CharField(blank=True, choices=[('MORNING', 'Morning Shift'), ('AFTERNOON', 'Afternoon Shift'), ('NIGHT', 'Night Shift')], max_length=20, null=True),
        ),
    ]
