# Generated by Django 5.1.4 on 2024-12-13 19:26

from django.db import migrations


def copy_shift_to_old_shift(apps, schema_editor):
    LaborMetric = apps.get_model('mining_operations', 'LaborMetric')
    db_alias = schema_editor.connection.alias

    # Copy shift values to old_shift field
    for labor_metric in LaborMetric.objects.using(db_alias).all():
        if isinstance(labor_metric.shift, str):
            labor_metric.old_shift = labor_metric.shift
            labor_metric.shift = None
            labor_metric.save()

def reverse_copy_shift(apps, schema_editor):
    LaborMetric = apps.get_model('mining_operations', 'LaborMetric')
    db_alias = schema_editor.connection.alias

    # Copy old_shift values back to shift field
    for labor_metric in LaborMetric.objects.using(db_alias).all():
        if labor_metric.old_shift:
            labor_metric.shift = labor_metric.old_shift
            labor_metric.save()

class Migration(migrations.Migration):

    dependencies = [
        ('mining_operations', '0016_historicallabormetric_old_shift_and_more'),
    ]

    operations = [
        migrations.RunPython(copy_shift_to_old_shift, reverse_copy_shift),
    ]
