# Generated by Django 5.1.4 on 2024-12-13 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mining_operations', '0017_copy_shift_values'),
    ]

    operations = [
    ]
