# Generated by Django 5.1.4 on 2024-12-13 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining_operations', '0020_make_shift_department_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailychemicalsused',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mining_operations.miningdepartment'),
        ),
        migrations.AlterField(
            model_name='dailyexplosivesused',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mining_operations.miningdepartment'),
        ),
        migrations.AlterField(
            model_name='labormetric',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labor_metrics', to='mining_operations.miningdepartment'),
        ),
        migrations.AlterField(
            model_name='labormetric',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labor_metrics', to='mining_operations.shift'),
        ),
        migrations.AlterField(
            model_name='safetyincident',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_incidents_ops', to='mining_operations.miningdepartment'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='mining_operations.miningdepartment'),
        ),
    ]
