# Generated by Django 5.1.4 on 2024-12-15 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mining_operations', '0026_cleanup_redundant_models'),
    ]

    operations = [
    ]
