# Generated by Django 5.1.4 on 2024-12-15 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mining_operations', '0030_make_hoisted_tonnage_consistent'),
    ]

    operations = [
    ]
