# Generated by Django 5.1.4 on 2024-12-21 18:21

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining_operations', '0032_historicalenvironmentalmetric_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEnergyUsage',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('electricity_kwh', models.FloatField(help_text='Daily electricity consumption in kilowatt-hours', validators=[django.core.validators.MinValueValidator(0)])),
                ('electricity_cost', models.DecimalField(decimal_places=2, help_text='Daily electricity cost in $', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('diesel_liters', models.FloatField(help_text='Daily diesel consumption in liters', validators=[django.core.validators.MinValueValidator(0)])),
                ('diesel_cost', models.DecimalField(decimal_places=2, help_text='Daily diesel cost in $', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_cost', models.DecimalField(decimal_places=2, help_text='Total energy cost for the day in $', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Energy Usage',
                'verbose_name_plural': 'historical Energy Usage',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AlterModelOptions(
            name='energyusage',
            options={'ordering': ['-date'], 'verbose_name': 'Energy Usage', 'verbose_name_plural': 'Energy Usage'},
        ),
        migrations.AddField(
            model_name='energyusage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='energyusage',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energyusage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddIndex(
            model_name='energyusage',
            index=models.Index(fields=['date'], name='mining_oper_date_19ad72_idx'),
        ),
        migrations.AddField(
            model_name='historicalenergyusage',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
