# Generated by Django 5.1.4 on 2024-12-23 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining_operations', '0033_historicalenergyusage_alter_energyusage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiningEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the equipment', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the equipment')),
                ('value_usd', models.DecimalField(decimal_places=2, help_text='Current value in USD', max_digits=12)),
                ('last_service_date', models.DateField(help_text='Date of the last service')),
                ('next_service_date', models.DateField(help_text='Date when next service is due')),
                ('service_interval_days', models.PositiveIntegerField(help_text='Number of days between services')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mining Equipment',
                'verbose_name_plural': 'Mining Equipment',
                'ordering': ['name'],
            },
        ),
    ]
