# Generated by Django 5.1.4 on 2024-12-23 23:50

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining_operations', '0035_populate_mining_equipment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('value_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_service_date', models.DateField()),
                ('next_service_date', models.DateField()),
                ('service_interval_days', models.IntegerField()),
                ('status', models.CharField(default='OK', max_length=20)),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment',
                'indexes': [models.Index(fields=['name'], name='mining_oper_name_36dd4e_idx'), models.Index(fields=['status'], name='mining_oper_status_f6d5fd_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEquipment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('value_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_service_date', models.DateField()),
                ('next_service_date', models.DateField()),
                ('service_interval_days', models.IntegerField()),
                ('status', models.CharField(default='OK', max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Equipment',
                'verbose_name_plural': 'historical Equipment',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
