# Generated by Django 5.1.4 on 2024-12-24 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining_operations', '0036_equipment_historicalequipment'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='equipment',
            name='mining_oper_name_36dd4e_idx',
        ),
        migrations.RemoveIndex(
            model_name='equipment',
            name='mining_oper_status_f6d5fd_idx',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='last_service_date',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='next_service_date',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='service_interval_days',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='value_usd',
        ),
        migrations.RemoveField(
            model_name='historicalequipment',
            name='last_service_date',
        ),
        migrations.RemoveField(
            model_name='historicalequipment',
            name='next_service_date',
        ),
        migrations.RemoveField(
            model_name='historicalequipment',
            name='service_interval_days',
        ),
        migrations.RemoveField(
            model_name='historicalequipment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='historicalequipment',
            name='value_usd',
        ),
        migrations.AddField(
            model_name='equipment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='mining_operations.miningdepartment'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalequipment',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalequipment',
            name='department',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mining_operations.miningdepartment'),
        ),
        migrations.AddField(
            model_name='historicalequipment',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalequipment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
