# Generated by Django 5.1.4 on 2024-12-24 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining_operations', '0037_remove_equipment_mining_oper_name_36dd4e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='last_service_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='next_service_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='service_interval_days',
            field=models.PositiveIntegerField(default=30, help_text='Number of days between services'),
        ),
        migrations.AddField(
            model_name='historicalequipment',
            name='last_service_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalequipment',
            name='next_service_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalequipment',
            name='service_interval_days',
            field=models.PositiveIntegerField(default=30, help_text='Number of days between services'),
        ),
    ]
