# Generated by Django 5.1.4 on 2024-12-24 00:59

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining_operations', '0038_equipment_last_service_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEquipmentRuntime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('running_hours', models.DecimalField(decimal_places=2, help_text='Hours the equipment was running during this day', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('idle_hours', models.DecimalField(decimal_places=2, help_text='Hours the equipment was idle during this day', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('downtime_hours', models.DecimalField(decimal_places=2, help_text='Hours the equipment was down for maintenance or repairs', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_runtimes', to='mining_operations.equipment')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_equipment', to='mining_operations.employee')),
                ('shift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_runtimes', to='mining_operations.shift')),
            ],
            options={
                'verbose_name': 'Daily Equipment Runtime',
                'verbose_name_plural': 'Daily Equipment Runtimes',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDailyEquipmentRuntime',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField()),
                ('running_hours', models.DecimalField(decimal_places=2, help_text='Hours the equipment was running during this day', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('idle_hours', models.DecimalField(decimal_places=2, help_text='Hours the equipment was idle during this day', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('downtime_hours', models.DecimalField(decimal_places=2, help_text='Hours the equipment was down for maintenance or repairs', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('equipment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mining_operations.equipment')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mining_operations.employee')),
                ('shift', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mining_operations.shift')),
            ],
            options={
                'verbose_name': 'historical Daily Equipment Runtime',
                'verbose_name_plural': 'historical Daily Equipment Runtimes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveField(
            model_name='equipmentmaintenancelog',
            name='heavy_machinery',
        ),
        migrations.RemoveField(
            model_name='equipmentmaintenancelog',
            name='milling_equipment',
        ),
        migrations.RemoveField(
            model_name='equipmentmaintenancelog',
            name='technician',
        ),
        migrations.RemoveField(
            model_name='goldmillingequipment',
            name='site',
        ),
        migrations.RemoveField(
            model_name='historicalequipmentmaintenancelog',
            name='milling_equipment',
        ),
        migrations.RemoveField(
            model_name='heavymachinery',
            name='department',
        ),
        migrations.RemoveField(
            model_name='heavymachinery',
            name='site',
        ),
        migrations.RemoveField(
            model_name='historicalequipmentmaintenancelog',
            name='heavy_machinery',
        ),
        migrations.RemoveField(
            model_name='historicalequipmentmaintenancelog',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalequipmentmaintenancelog',
            name='technician',
        ),
        migrations.RemoveField(
            model_name='historicalgoldmillingequipment',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalgoldmillingequipment',
            name='site',
        ),
        migrations.RemoveField(
            model_name='historicalheavymachinery',
            name='department',
        ),
        migrations.RemoveField(
            model_name='historicalheavymachinery',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalheavymachinery',
            name='site',
        ),
        migrations.DeleteModel(
            name='MiningEquipment',
        ),
        migrations.DeleteModel(
            name='EquipmentMaintenanceLog',
        ),
        migrations.DeleteModel(
            name='GoldMillingEquipment',
        ),
        migrations.DeleteModel(
            name='HeavyMachinery',
        ),
        migrations.DeleteModel(
            name='HistoricalEquipmentMaintenanceLog',
        ),
        migrations.DeleteModel(
            name='HistoricalGoldMillingEquipment',
        ),
        migrations.DeleteModel(
            name='HistoricalHeavyMachinery',
        ),
        migrations.AddIndex(
            model_name='dailyequipmentruntime',
            index=models.Index(fields=['date'], name='mining_oper_date_834731_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyequipmentruntime',
            index=models.Index(fields=['equipment'], name='mining_oper_equipme_0c09af_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyequipmentruntime',
            index=models.Index(fields=['shift'], name='mining_oper_shift_i_3431ad_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyequipmentruntime',
            index=models.Index(fields=['operator'], name='mining_oper_operato_2c262b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyequipmentruntime',
            unique_together={('date', 'equipment')},
        ),
    ]
