# Generated by Django 5.1.4 on 2024-12-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining_operations', '0040_miningequipment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalequipmentrunningtime',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='historicalequipmentrunningtime',
            name='history_user',
        ),
        migrations.AddField(
            model_name='historicalminingsite',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='miningsite',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='EquipmentRunningTime',
        ),
        migrations.DeleteModel(
            name='HistoricalEquipmentRunningTime',
        ),
    ]
