# Generated by Django 5.1.4 on 2024-12-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining_operations', '0041_remove_historicalequipmentrunningtime_equipment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsafetyincident',
            name='incident_type',
            field=models.CharField(choices=[('equipment_failure', 'Equipment Failure'), ('personal_injury', 'Personal Injury'), ('environmental', 'Environmental'), ('near_miss', 'Near Miss'), ('property_damage', 'Property Damage')], max_length=30),
        ),
        migrations.AlterField(
            model_name='safetyincident',
            name='incident_type',
            field=models.CharField(choices=[('equipment_failure', 'Equipment Failure'), ('personal_injury', 'Personal Injury'), ('environmental', 'Environmental'), ('near_miss', 'Near Miss'), ('property_damage', 'Property Damage')], max_length=30),
        ),
    ]
